// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  var URL, changeCount, tabChanged, updateBadge, url2domain, urlCheck;

  chrome.runtime.onInstalled.addListener(function(details) {
    return console.log('previousVersion', details.previousVersion);
  });

  ({
    cur_domain: null
  });

  urlCheck = function(url) {
    var a;
    a = document.createElement('a');
    a.href = url;
    if (a.protocol === 'http:' || a.protocol === 'https:') {
      return true;
    } else {
      return false;
    }
  };

  url2domain = function(url) {
    var a;
    a = document.createElement('a');
    a.href = url;
    return a.hostname;
  };

  updateBadge = function(url) {
    return chrome.browserAction.setBadgeText({
      text: JSON.stringify(URL.count)
    });
  };

  changeCount = function(url) {
    if (localStorage.getItem("url-info")) {
      URL.data = JSON.parse(localStorage.getItem("url-info"));
      if (URL.data[url]) {
        URL.count = URL.data[url];
      } else {
        URL.count = 0;
      }
      return updateBadge(url);
    }
  };

  tabChanged = function(url) {
    var cur_domain;
    cur_domain = url;
    return changeCount(cur_domain);
  };

  chrome.tabs.onActivated.addListener(function(activeInfo) {
    var curTabId;
    curTabId = activeInfo.tabId;
    return chrome.tabs.get(activeInfo.tabId, function(tab) {
      var domain;
      if (!urlCheck(tab.url)) {
        return;
      }
      domain = url2domain(tab.url);
      if (domain) {
        return tabChanged(domain);
      }
    });
  });

  chrome.alarms.onAlarm.addListener(function(alarm) {
    if (alarm.name === "update") {
      if (!URL.curTabId) {
        return;
      }
      chrome.tabs.get(URL.curTabId, function(tab) {
        var domain;
        if (!urlCheck(tab.url)) {
          return;
        }
        if (tab.url) {
          return domain = url2domain(tab.url);
        }
      });
      return changeCount(domain);
    }
  });

  chrome.tabs.onUpdated.addListener(function(tabId, info) {
    if (info.status === "complete") {
      return chrome.tabs.get(tabId, function(tab) {
        var domain;
        if (!urlCheck(tab.url)) {
          return;
        }
        domain = url2domain(tab.url);
        localStorage.setItem("get-domain", JSON.stringify(domain));
        return tabChanged(domain);
      });
    }
  });

  chrome.alarms.create("update", {
    periodInMinutes: 0.02
  });

  URL = {
    data: {},
    count: 0
  };

}).call(this);
