// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  var tabChanged, url2domain, urlCheck;

  chrome.runtime.onInstalled.addListener(function(details) {
    return console.log('previousVersion', details.previousVersion);
  });

  ({
    cur_domain: null
  });

  tabChanged = function(url) {
    var cur_domain;
    cur_domain = url;
    return localStorage.setItem("get-domain", JSON.stringify(cur_domain));
  };

  urlCheck = function(url) {
    var a;
    a = document.createElement('a');
    a.href = url;
    if (a.protocol === 'http:' || a.protocol === 'https:') {
      return true;
    } else {
      return false;
    }
  };

  url2domain = function(url) {
    var a;
    a = document.createElement('a');
    a.href = url;
    return a.hostname;
  };

  chrome.tabs.onActivated.addListener(function(activeInfo) {
    var curTabId;
    console.log("Select " + activeInfo.tabId + " ");
    curTabId = activeInfo.tabId;
    return chrome.tabs.get(activeInfo.tabId, function(tab) {
      var domain;
      if (!urlCheck(tab.url)) {
        return;
      }
      domain = url2domain(tab.url);
      if (domain) {
        return tabChanged(domain);
      }
    });
  });

  chrome.tabs.onUpdated.addListener(function(tabId, info) {
    if (info.status === "complete") {
      return chrome.tabs.get(tabId, function(tab) {
        var cur_domain, domain;
        if (!urlCheck(tab.url)) {
          return;
        }
        domain = url2domain(tab.url);
        cur_domain = domain;
        return localStorage.setItem("get-domain", JSON.stringify(cur_domain));
      });
    }
  });

}).call(this);
