// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  chrome.runtime.onInstalled.addListener(function(details) {
    return console.log('previousVersion', details.previousVersion);
  });

}).call(this);
