// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  counter;
  var counter, email, foo, loadData, name, password, retrievedObject, tab_check, user, yourGlobalVariable;

  if (localStorage.getItem('counter')) {
    counter = localStorage.getItem('counter');
  }

  console.log(counter);

  yourGlobalVariable = 0;

  user = {
    email: null,
    nameString: null
  };

  email = document.getElementById('inputEmail');

  name = document.getElementById('inputName');

  password = document.getElementById('inputPassword');

  retrievedObject;

  foo;

  if (localStorage.getItem('memory', user) !== null) {
    retrievedObject = localStorage.getItem('memory', user);
    foo = JSON.parse(retrievedObject);
    name.setAttribute('value', foo.nameString);
    email.setAttribute('value', foo.email);
  }

  tab_check = false;

  $('#changer').click(function() {
    if (tab_check === false) {
      $('#sign_up').addClass('hidden');
      $('#sign_in').removeClass('hidden');
      $('#changer').html('Sign Up');
      return tab_check = true;
    } else {
      $('#sign_up').removeClass('hidden');
      $('#sign_in').addClass('hidden');
      $('#changer').html('Sign In');
      return tab_check = false;
    }
  });

  $('#submitSignUp').click(function() {
    if ($('#sign_up')[0].checkValidity()) {
      alert('SMTH');
      return $.ajax({
        url: 'http://127.0.0.1:8000/api/v1/my_user/',
        type: 'POST',
        data: JSON.stringify({
          email: $('#inputEmail').val(),
          name: $('#inputName').val(),
          password: $('#inputPassword').val()
        }),
        contentType: 'application/json',
        success: function() {
          return alert("Registrated");
        }
      });
    }
  });

  loadData = function() {
    $.ajax({
      url: 'http://127.0.0.1:8000/api/v1/comment/',
      success: function(result) {
        var email;
        var contDiv, day, dd, globalDiv, gravatar, i, img, imgDiv, mesDiv, mesString, mm, month, nameString, nameUser, newDiv, sep, time, timeDiv, today, year, yyyy;
        if (counter < result.objects.length) {
          i = counter + 1;
          while (i < result.objects.length) {
            contDiv = void 0;
            dd = void 0;
            email = void 0;
            globalDiv = void 0;
            gravatar = void 0;
            img = void 0;
            imgDiv = void 0;
            mesDiv = void 0;
            mesString = void 0;
            mm = void 0;
            nameString = void 0;
            nameUser = void 0;
            newDiv = void 0;
            sep = void 0;
            timeDiv = void 0;
            today = void 0;
            yyyy = void 0;
            mesString = document.getElementById('focusedInput').value;
            globalDiv = document.getElementById('omg');
            if (yourGlobalVariable > 0) {
              sep = document.createElement('div');
              sep.setAttribute('class', 'list-group-separator');
              globalDiv.appendChild(sep);
            }
            newDiv = document.createElement('div');
            newDiv.setAttribute('class', 'list-group-item');
            globalDiv.appendChild(newDiv);
            imgDiv = document.createElement('div');
            imgDiv.setAttribute('class', 'row-action-primary');
            newDiv.appendChild(imgDiv);
            img = document.createElement('img');
            img.setAttribute('class', 'circle');
            gravatar = result.objects[i].image;
            img.setAttribute('src', gravatar);
            imgDiv.appendChild(img);
            contDiv = document.createElement('div');
            contDiv.setAttribute('class', 'row-content');
            newDiv.appendChild(contDiv);
            timeDiv = document.createElement('div');
            timeDiv.setAttribute('class', 'least-content');
            time = result.objects[i].pub_time;
            time = time.substring(0, 10);
            day = time.substring(8, 10);
            month = time.substring(5, 7);
            year = time.substring(2, 4);
            timeDiv.appendChild(document.createTextNode(day + '.' + month + '.' + year));
            contDiv.appendChild(timeDiv);
            nameUser = document.createElement('h4');
            nameUser.setAttribute('class', 'list-group-item-heading');
            nameUser.appendChild(document.createTextNode(result.objects[i].author_title));
            contDiv.appendChild(nameUser);
            mesDiv = document.createElement('p');
            mesDiv.setAttribute('class', 'list-group-item-text');
            mesDiv.appendChild(document.createTextNode(result.objects[i].text));
            contDiv.appendChild(mesDiv);
            yourGlobalVariable++;
            counter = i;
            localStorage.setItem('counter', counter);
            console.log(counter + ' ' + i);
            i++;
          }
        }
      }
    });
  };

  loadData();

  return;

}).call(this);
